export interface CropConfig {
  id: string;
  name: string;
  category: string;
  defaultRowSpacing: number; // in meters
  defaultPlantSpacing: number; // in meters
  minPh: number;
  maxPh: number;
  minTemp: number; // in °C
  maxTemp: number; // in °C
  minMoisture: number; // in %
  maxMoisture: number; // in %
  nitrogen: number; // optimum N in mg/kg
  phosphorus: number; // optimum P in mg/kg
  potassium: number; // optimum K in mg/kg
  minEc: number; // in µS/cm
  maxEc: number; // in µS/cm
  yieldFactor: number; // Base yield in kg per plant
}

export const CROPS_CATALOGUE: CropConfig[] = [
  {
    id: "rice",
    name: "Rice (Paddy)",
    category: "Cereals",
    defaultRowSpacing: 0.20,
    defaultPlantSpacing: 0.15,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 22,
    maxTemp: 35,
    minMoisture: 50,
    maxMoisture: 90,
    nitrogen: 80,
    phosphorus: 40,
    potassium: 40,
    minEc: 500,
    maxEc: 1500,
    yieldFactor: 0.014,
  },
  {
    id: "wheat",
    name: "Wheat",
    category: "Cereals",
    defaultRowSpacing: 0.22,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 15,
    maxTemp: 25,
    minMoisture: 30,
    maxMoisture: 60,
    nitrogen: 90,
    phosphorus: 50,
    potassium: 50,
    minEc: 600,
    maxEc: 1600,
    yieldFactor: 0.012,
  },
  {
    id: "maize",
    name: "Maize (Corn)",
    category: "Cereals",
    defaultRowSpacing: 0.60,
    defaultPlantSpacing: 0.20,
    minPh: 5.8,
    maxPh: 7.2,
    minTemp: 18,
    maxTemp: 30,
    minMoisture: 40,
    maxMoisture: 70,
    nitrogen: 120,
    phosphorus: 60,
    potassium: 60,
    minEc: 800,
    maxEc: 2000,
    yieldFactor: 0.15,
  },
  {
    id: "barley",
    name: "Barley",
    category: "Cereals",
    defaultRowSpacing: 0.22,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 8.0,
    minTemp: 12,
    maxTemp: 24,
    minMoisture: 30,
    maxMoisture: 55,
    nitrogen: 70,
    phosphorus: 40,
    potassium: 40,
    minEc: 700,
    maxEc: 1800,
    yieldFactor: 0.011,
  },
  {
    id: "sorghum",
    name: "Sorghum (Jowar)",
    category: "Millets",
    defaultRowSpacing: 0.45,
    defaultPlantSpacing: 0.15,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 20,
    maxTemp: 32,
    minMoisture: 25,
    maxMoisture: 50,
    nitrogen: 80,
    phosphorus: 40,
    potassium: 40,
    minEc: 600,
    maxEc: 1500,
    yieldFactor: 0.08,
  },
  {
    id: "pearl_millet",
    name: "Pearl Millet (Bajra)",
    category: "Millets",
    defaultRowSpacing: 0.45,
    defaultPlantSpacing: 0.12,
    minPh: 6.5,
    maxPh: 8.0,
    minTemp: 22,
    maxTemp: 35,
    minMoisture: 20,
    maxMoisture: 45,
    nitrogen: 60,
    phosphorus: 30,
    potassium: 30,
    minEc: 500,
    maxEc: 1400,
    yieldFactor: 0.06,
  },
  {
    id: "finger_millet",
    name: "Finger Millet (Ragi)",
    category: "Millets",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 5.0,
    maxPh: 7.0,
    minTemp: 18,
    maxTemp: 30,
    minMoisture: 30,
    maxMoisture: 60,
    nitrogen: 50,
    phosphorus: 30,
    potassium: 30,
    minEc: 400,
    maxEc: 1200,
    yieldFactor: 0.04,
  },
  {
    id: "foxtail_millet",
    name: "Foxtail Millet (Kangni)",
    category: "Millets",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 5.5,
    maxPh: 7.0,
    minTemp: 18,
    maxTemp: 32,
    minMoisture: 25,
    maxMoisture: 50,
    nitrogen: 40,
    phosphorus: 25,
    potassium: 25,
    minEc: 400,
    maxEc: 1000,
    yieldFactor: 0.03,
  },
  {
    id: "soybean",
    name: "Soybean",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.45,
    defaultPlantSpacing: 0.08,
    minPh: 6.0,
    maxPh: 7.0,
    minTemp: 20,
    maxTemp: 30,
    minMoisture: 40,
    maxMoisture: 65,
    nitrogen: 30,
    phosphorus: 60,
    potassium: 60,
    minEc: 400,
    maxEc: 1200,
    yieldFactor: 0.05,
  },
  {
    id: "chickpea",
    name: "Chickpea (Gram)",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 15,
    maxTemp: 28,
    minMoisture: 25,
    maxMoisture: 50,
    nitrogen: 20,
    phosphorus: 50,
    potassium: 40,
    minEc: 500,
    maxEc: 1200,
    yieldFactor: 0.03,
  },
  {
    id: "pigeon_pea",
    name: "Pigeon Pea (Tur/Arhar)",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.60,
    defaultPlantSpacing: 0.20,
    minPh: 6.5,
    maxPh: 7.5,
    minTemp: 18,
    maxTemp: 32,
    minMoisture: 30,
    maxMoisture: 55,
    nitrogen: 25,
    phosphorus: 50,
    potassium: 45,
    minEc: 400,
    maxEc: 1300,
    yieldFactor: 0.09,
  },
  {
    id: "green_gram",
    name: "Green Gram (Mung Bean)",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 6.2,
    maxPh: 7.2,
    minTemp: 22,
    maxTemp: 35,
    minMoisture: 30,
    maxMoisture: 55,
    nitrogen: 20,
    phosphorus: 45,
    potassium: 40,
    minEc: 400,
    maxEc: 1100,
    yieldFactor: 0.02,
  },
  {
    id: "black_gram",
    name: "Black Gram (Urad Bean)",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 22,
    maxTemp: 35,
    minMoisture: 30,
    maxMoisture: 55,
    nitrogen: 20,
    phosphorus: 45,
    potassium: 40,
    minEc: 400,
    maxEc: 1100,
    yieldFactor: 0.02,
  },
  {
    id: "lentil",
    name: "Lentil (Masur)",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.25,
    defaultPlantSpacing: 0.08,
    minPh: 6.0,
    maxPh: 7.2,
    minTemp: 12,
    maxTemp: 25,
    minMoisture: 25,
    maxMoisture: 50,
    nitrogen: 20,
    phosphorus: 40,
    potassium: 40,
    minEc: 400,
    maxEc: 1100,
    yieldFactor: 0.015,
  },
  {
    id: "kidney_beans",
    name: "Kidney Beans (Rajma)",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.45,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 6.8,
    minTemp: 15,
    maxTemp: 25,
    minMoisture: 40,
    maxMoisture: 60,
    nitrogen: 40,
    phosphorus: 60,
    potassium: 50,
    minEc: 400,
    maxEc: 1200,
    yieldFactor: 0.04,
  },
  {
    id: "cowpea",
    name: "Cowpea (Lobia)",
    category: "Pulses & Legumes",
    defaultRowSpacing: 0.45,
    defaultPlantSpacing: 0.15,
    minPh: 5.5,
    maxPh: 7.0,
    minTemp: 20,
    maxTemp: 32,
    minMoisture: 30,
    maxMoisture: 60,
    nitrogen: 20,
    phosphorus: 40,
    potassium: 40,
    minEc: 400,
    maxEc: 1200,
    yieldFactor: 0.04,
  },
  {
    id: "mustard",
    name: "Mustard (Sarson)",
    category: "Oilseeds",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 10,
    maxTemp: 22,
    minMoisture: 30,
    maxMoisture: 55,
    nitrogen: 80,
    phosphorus: 40,
    potassium: 40,
    minEc: 600,
    maxEc: 1500,
    yieldFactor: 0.03,
  },
  {
    id: "groundnut",
    name: "Groundnut (Peanut)",
    category: "Oilseeds",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 6.5,
    minTemp: 22,
    maxTemp: 32,
    minMoisture: 35,
    maxMoisture: 60,
    nitrogen: 25,
    phosphorus: 50,
    potassium: 50,
    minEc: 400,
    maxEc: 1200,
    yieldFactor: 0.04,
  },
  {
    id: "sunflower",
    name: "Sunflower",
    category: "Oilseeds",
    defaultRowSpacing: 0.60,
    defaultPlantSpacing: 0.25,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 18,
    maxTemp: 30,
    minMoisture: 35,
    maxMoisture: 65,
    nitrogen: 80,
    phosphorus: 60,
    potassium: 80,
    minEc: 600,
    maxEc: 1600,
    yieldFactor: 0.08,
  },
  {
    id: "sesame",
    name: "Sesame (Til)",
    category: "Oilseeds",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.10,
    minPh: 5.5,
    maxPh: 8.0,
    minTemp: 22,
    maxTemp: 35,
    minMoisture: 20,
    maxMoisture: 45,
    nitrogen: 40,
    phosphorus: 30,
    potassium: 30,
    minEc: 400,
    maxEc: 1200,
    yieldFactor: 0.02,
  },
  {
    id: "safflower",
    name: "Safflower",
    category: "Oilseeds",
    defaultRowSpacing: 0.45,
    defaultPlantSpacing: 0.15,
    minPh: 6.0,
    maxPh: 8.0,
    minTemp: 15,
    maxTemp: 30,
    minMoisture: 20,
    maxMoisture: 45,
    nitrogen: 50,
    phosphorus: 30,
    potassium: 30,
    minEc: 500,
    maxEc: 1500,
    yieldFactor: 0.03,
  },
  {
    id: "cotton",
    name: "Cotton (Kapas)",
    category: "Fiber Crops",
    defaultRowSpacing: 0.90,
    defaultPlantSpacing: 0.30,
    minPh: 6.0,
    maxPh: 8.0,
    minTemp: 20,
    maxTemp: 35,
    minMoisture: 30,
    maxMoisture: 60,
    nitrogen: 100,
    phosphorus: 50,
    potassium: 80,
    minEc: 800,
    maxEc: 2200,
    yieldFactor: 0.25,
  },
  {
    id: "sugarcane",
    name: "Sugarcane",
    category: "Sugar Crops",
    defaultRowSpacing: 1.20,
    defaultPlantSpacing: 0.30,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 20,
    maxTemp: 32,
    minMoisture: 55,
    maxMoisture: 85,
    nitrogen: 150,
    phosphorus: 80,
    potassium: 120,
    minEc: 1000,
    maxEc: 2500,
    yieldFactor: 8.5,
  },
  {
    id: "jute",
    name: "Jute",
    category: "Fiber Crops",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.08,
    minPh: 5.0,
    maxPh: 7.5,
    minTemp: 24,
    maxTemp: 37,
    minMoisture: 60,
    maxMoisture: 90,
    nitrogen: 80,
    phosphorus: 40,
    potassium: 60,
    minEc: 500,
    maxEc: 1500,
    yieldFactor: 0.08,
  },
  {
    id: "potato",
    name: "Potato",
    category: "Tubers & Root Crops",
    defaultRowSpacing: 0.60,
    defaultPlantSpacing: 0.20,
    minPh: 5.0,
    maxPh: 6.0,
    minTemp: 15,
    maxTemp: 22,
    minMoisture: 45,
    maxMoisture: 75,
    nitrogen: 120,
    phosphorus: 80,
    potassium: 150,
    minEc: 800,
    maxEc: 2000,
    yieldFactor: 0.45,
  },
  {
    id: "sweet_potato",
    name: "Sweet Potato",
    category: "Tubers & Root Crops",
    defaultRowSpacing: 0.75,
    defaultPlantSpacing: 0.25,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 20,
    maxTemp: 30,
    minMoisture: 40,
    maxMoisture: 70,
    nitrogen: 60,
    phosphorus: 60,
    potassium: 120,
    minEc: 600,
    maxEc: 1600,
    yieldFactor: 0.35,
  },
  {
    id: "cassava",
    name: "Cassava (Tapioca)",
    category: "Tubers & Root Crops",
    defaultRowSpacing: 0.90,
    defaultPlantSpacing: 0.90,
    minPh: 5.0,
    maxPh: 6.5,
    minTemp: 22,
    maxTemp: 32,
    minMoisture: 35,
    maxMoisture: 70,
    nitrogen: 80,
    phosphorus: 60,
    potassium: 120,
    minEc: 500,
    maxEc: 1500,
    yieldFactor: 2.2,
  },
  {
    id: "tomato",
    name: "Tomato",
    category: "Vegetables",
    defaultRowSpacing: 0.60,
    defaultPlantSpacing: 0.45,
    minPh: 6.0,
    maxPh: 6.8,
    minTemp: 18,
    maxTemp: 28,
    minMoisture: 45,
    maxMoisture: 70,
    nitrogen: 100,
    phosphorus: 80,
    potassium: 120,
    minEc: 700,
    maxEc: 1800,
    yieldFactor: 0.65,
  },
  {
    id: "onion",
    name: "Onion",
    category: "Vegetables",
    defaultRowSpacing: 0.15,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 7.0,
    minTemp: 12,
    maxTemp: 25,
    minMoisture: 40,
    maxMoisture: 65,
    nitrogen: 90,
    phosphorus: 60,
    potassium: 80,
    minEc: 600,
    maxEc: 1500,
    yieldFactor: 0.12,
  },
  {
    id: "garlic",
    name: "Garlic",
    category: "Vegetables",
    defaultRowSpacing: 0.15,
    defaultPlantSpacing: 0.10,
    minPh: 6.0,
    maxPh: 7.0,
    minTemp: 12,
    maxTemp: 25,
    minMoisture: 35,
    maxMoisture: 60,
    nitrogen: 80,
    phosphorus: 50,
    potassium: 80,
    minEc: 600,
    maxEc: 1400,
    yieldFactor: 0.08,
  },
  {
    id: "ginger",
    name: "Ginger",
    category: "Spices",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.20,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 20,
    maxTemp: 30,
    minMoisture: 55,
    maxMoisture: 80,
    nitrogen: 75,
    phosphorus: 50,
    potassium: 100,
    minEc: 500,
    maxEc: 1300,
    yieldFactor: 0.25,
  },
  {
    id: "turmeric",
    name: "Turmeric",
    category: "Spices",
    defaultRowSpacing: 0.30,
    defaultPlantSpacing: 0.20,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 20,
    maxTemp: 30,
    minMoisture: 55,
    maxMoisture: 80,
    nitrogen: 80,
    phosphorus: 60,
    potassium: 120,
    minEc: 500,
    maxEc: 1400,
    yieldFactor: 0.30,
  },
  {
    id: "chilli",
    name: "Chilli (Red Pepper)",
    category: "Vegetables",
    defaultRowSpacing: 0.45,
    defaultPlantSpacing: 0.30,
    minPh: 6.0,
    maxPh: 7.0,
    minTemp: 20,
    maxTemp: 30,
    minMoisture: 40,
    maxMoisture: 65,
    nitrogen: 80,
    phosphorus: 60,
    potassium: 80,
    minEc: 600,
    maxEc: 1500,
    yieldFactor: 0.18,
  },
  {
    id: "black_pepper",
    name: "Black Pepper",
    category: "Spices",
    defaultRowSpacing: 1.50,
    defaultPlantSpacing: 1.50,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 22,
    maxTemp: 32,
    minMoisture: 60,
    maxMoisture: 85,
    nitrogen: 80,
    phosphorus: 40,
    potassium: 100,
    minEc: 500,
    maxEc: 1200,
    yieldFactor: 0.75,
  },
  {
    id: "cardamom",
    name: "Cardamom",
    category: "Spices",
    defaultRowSpacing: 2.00,
    defaultPlantSpacing: 2.00,
    minPh: 5.0,
    maxPh: 6.0,
    minTemp: 15,
    maxTemp: 25,
    minMoisture: 65,
    maxMoisture: 90,
    nitrogen: 60,
    phosphorus: 60,
    potassium: 80,
    minEc: 400,
    maxEc: 1000,
    yieldFactor: 0.50,
  },
  {
    id: "tea",
    name: "Tea",
    category: "Plantation Crops",
    defaultRowSpacing: 1.00,
    defaultPlantSpacing: 0.60,
    minPh: 4.5,
    maxPh: 5.5,
    minTemp: 18,
    maxTemp: 28,
    minMoisture: 55,
    maxMoisture: 80,
    nitrogen: 100,
    phosphorus: 50,
    potassium: 60,
    minEc: 400,
    maxEc: 1000,
    yieldFactor: 0.20,
  },
  {
    id: "coffee",
    name: "Coffee (Arabica)",
    category: "Plantation Crops",
    defaultRowSpacing: 2.00,
    defaultPlantSpacing: 1.50,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 15,
    maxTemp: 25,
    minMoisture: 50,
    maxMoisture: 75,
    nitrogen: 100,
    phosphorus: 40,
    potassium: 120,
    minEc: 500,
    maxEc: 1200,
    yieldFactor: 0.80,
  },
  {
    id: "coconut",
    name: "Coconut",
    category: "Plantation Crops",
    defaultRowSpacing: 7.50,
    defaultPlantSpacing: 7.50,
    minPh: 5.2,
    maxPh: 8.0,
    minTemp: 22,
    maxTemp: 32,
    minMoisture: 45,
    maxMoisture: 80,
    nitrogen: 120,
    phosphorus: 80,
    potassium: 200,
    minEc: 800,
    maxEc: 2500,
    yieldFactor: 15.0,
  },
  {
    id: "rubber",
    name: "Rubber",
    category: "Plantation Crops",
    defaultRowSpacing: 4.50,
    defaultPlantSpacing: 3.00,
    minPh: 4.5,
    maxPh: 6.0,
    minTemp: 24,
    maxTemp: 30,
    minMoisture: 60,
    maxMoisture: 85,
    nitrogen: 80,
    phosphorus: 60,
    potassium: 80,
    minEc: 400,
    maxEc: 1000,
    yieldFactor: 2.5,
  },
  {
    id: "tobacco",
    name: "Tobacco",
    category: "Cash Crops",
    defaultRowSpacing: 0.90,
    defaultPlantSpacing: 0.45,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 20,
    maxTemp: 30,
    minMoisture: 40,
    maxMoisture: 65,
    nitrogen: 80,
    phosphorus: 50,
    potassium: 100,
    minEc: 600,
    maxEc: 1800,
    yieldFactor: 0.30,
  },
  {
    id: "banana",
    name: "Banana",
    category: "Fruits",
    defaultRowSpacing: 2.40,
    defaultPlantSpacing: 2.40,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 22,
    maxTemp: 32,
    minMoisture: 55,
    maxMoisture: 80,
    nitrogen: 150,
    phosphorus: 90,
    potassium: 250,
    minEc: 800,
    maxEc: 2000,
    yieldFactor: 12.0,
  },
  {
    id: "mango",
    name: "Mango",
    category: "Fruits",
    defaultRowSpacing: 10.0,
    defaultPlantSpacing: 10.0,
    minPh: 5.5,
    maxPh: 7.5,
    minTemp: 22,
    maxTemp: 35,
    minMoisture: 35,
    maxMoisture: 65,
    nitrogen: 100,
    phosphorus: 60,
    potassium: 100,
    minEc: 600,
    maxEc: 1500,
    yieldFactor: 25.0,
  },
  {
    id: "apple",
    name: "Apple",
    category: "Fruits",
    defaultRowSpacing: 4.00,
    defaultPlantSpacing: 2.50,
    minPh: 6.0,
    maxPh: 7.0,
    minTemp: 10,
    maxTemp: 24,
    minMoisture: 40,
    maxMoisture: 65,
    nitrogen: 90,
    phosphorus: 50,
    potassium: 100,
    minEc: 500,
    maxEc: 1400,
    yieldFactor: 10.0,
  },
  {
    id: "orange",
    name: "Citrus (Orange)",
    category: "Fruits",
    defaultRowSpacing: 5.00,
    defaultPlantSpacing: 5.00,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 18,
    maxTemp: 30,
    minMoisture: 40,
    maxMoisture: 70,
    nitrogen: 100,
    phosphorus: 60,
    potassium: 80,
    minEc: 600,
    maxEc: 1600,
    yieldFactor: 12.0,
  },
  {
    id: "grape",
    name: "Grape",
    category: "Fruits",
    defaultRowSpacing: 3.00,
    defaultPlantSpacing: 1.50,
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 15,
    maxTemp: 32,
    minMoisture: 35,
    maxMoisture: 60,
    nitrogen: 80,
    phosphorus: 60,
    potassium: 120,
    minEc: 600,
    maxEc: 1800,
    yieldFactor: 4.5,
  },
  {
    id: "guava",
    name: "Guava",
    category: "Fruits",
    defaultRowSpacing: 5.00,
    defaultPlantSpacing: 5.00,
    minPh: 5.0,
    maxPh: 8.2,
    minTemp: 20,
    maxTemp: 32,
    minMoisture: 35,
    maxMoisture: 65,
    nitrogen: 80,
    phosphorus: 50,
    potassium: 80,
    minEc: 500,
    maxEc: 1600,
    yieldFactor: 8.0,
  },
  {
    id: "papaya",
    name: "Papaya",
    category: "Fruits",
    defaultRowSpacing: 2.00,
    defaultPlantSpacing: 2.00,
    minPh: 6.0,
    maxPh: 6.5,
    minTemp: 22,
    maxTemp: 32,
    minMoisture: 50,
    maxMoisture: 75,
    nitrogen: 120,
    phosphorus: 80,
    potassium: 150,
    minEc: 600,
    maxEc: 1500,
    yieldFactor: 6.0,
  },
  {
    id: "pomegranate",
    name: "Pomegranate",
    category: "Fruits",
    defaultRowSpacing: 4.00,
    defaultPlantSpacing: 3.00,
    minPh: 6.0,
    maxPh: 8.0,
    minTemp: 20,
    maxTemp: 35,
    minMoisture: 25,
    maxMoisture: 50,
    nitrogen: 80,
    phosphorus: 50,
    potassium: 80,
    minEc: 600,
    maxEc: 1800,
    yieldFactor: 5.0,
  },
  {
    id: "watermelon",
    name: "Watermelon",
    category: "Fruits",
    defaultRowSpacing: 1.80,
    defaultPlantSpacing: 0.90,
    minPh: 6.0,
    maxPh: 6.8,
    minTemp: 22,
    maxTemp: 32,
    minMoisture: 40,
    maxMoisture: 65,
    nitrogen: 100,
    phosphorus: 60,
    potassium: 100,
    minEc: 600,
    maxEc: 1500,
    yieldFactor: 3.5,
  },
  {
    id: "strawberry",
    name: "Strawberry",
    category: "Fruits",
    defaultRowSpacing: 0.35,
    defaultPlantSpacing: 0.25,
    minPh: 5.5,
    maxPh: 6.5,
    minTemp: 15,
    maxTemp: 25,
    minMoisture: 45,
    maxMoisture: 70,
    nitrogen: 60,
    phosphorus: 50,
    potassium: 80,
    minEc: 500,
    maxEc: 1200,
    yieldFactor: 0.15,
  },
];
